// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlP2dLDhQHPXST8OT48AmVLiv_ngXiJio',
    appId: '1:1041958741163:web:6314d3fb155c76d5b043ee',
    messagingSenderId: '1041958741163',
    projectId: 'orbitpatter',
    authDomain: 'orbitpatter.firebaseapp.com',
    storageBucket: 'orbitpatter.firebasestorage.app',
    measurementId: 'G-CK0BLM3F1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA53J2mePq6JZqDhVxH7qYetuSLylkKuVY',
    appId: '1:1041958741163:android:61dacb34902b6756b043ee',
    messagingSenderId: '1041958741163',
    projectId: 'orbitpatter',
    storageBucket: 'orbitpatter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBymqcgh5cwglDWJcAKaI-XlPJlLZhKXiU',
    appId: '1:1041958741163:ios:0c5ae2c216660be2b043ee',
    messagingSenderId: '1041958741163',
    projectId: 'orbitpatter',
    storageBucket: 'orbitpatter.firebasestorage.app',
    iosClientId: '1041958741163-ushht903ik8htri3heqana8tkeprel6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.orbitpatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBymqcgh5cwglDWJcAKaI-XlPJlLZhKXiU',
    appId: '1:1041958741163:ios:0c5ae2c216660be2b043ee',
    messagingSenderId: '1041958741163',
    projectId: 'orbitpatter',
    storageBucket: 'orbitpatter.firebasestorage.app',
    iosClientId: '1041958741163-ushht903ik8htri3heqana8tkeprel6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.orbitpatter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlP2dLDhQHPXST8OT48AmVLiv_ngXiJio',
    appId: '1:1041958741163:web:6f1b6fb821a35e98b043ee',
    messagingSenderId: '1041958741163',
    projectId: 'orbitpatter',
    authDomain: 'orbitpatter.firebaseapp.com',
    storageBucket: 'orbitpatter.firebasestorage.app',
    measurementId: 'G-3KNZDEXB2R',
  );
}
